<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="HEC.RAS.Ras.Mapper" Version="0.1.0.1576-dev" />
	</ItemGroup>
	
</Project>
